[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "kometra-benchmark"
version = "1.0.0"
description = "Astrometric & Morphological Validation Suite for Cometary Centroiding"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "GPL-3.0-or-later" }
authors = [
    { name = "Fabio Genovese" }
]
dependencies = [
    "numpy>=1.20.0",
    "astropy>=5.0.0",
    "matplotlib>=3.3.0",
    "pandas>=1.2.0"
]

[project.urls]
Homepage = "https://github.com/Genofabio/comet-centroiding-benchmark"
Dataset = "https://doi.org/10.5281/zenodo.22014532"